FROM golang:1.25-alpine3.21@sha256:3289aac2aac769e031d644313d094dbda745f28af81cd7a94137e73eefd58b33 AS builder

LABEL org.opencontainers.image.title="opentofu"
LABEL org.opencontainers.image.authors="iodeslykos <42@iodeslykos.com>"
LABEL org.opencontainers.image.url="https://opentofu.org"
LABEL org.opencontainers.image.source="https://github.com/opentofu/opentofu/"

ARG build_arch=amd64
ARG build_os=linux
ARG workdir=/go/src/github.com/opentofu/opentofu
ARG opentf_branch=main

ENV PATH /go/bin:/usr/local/go/bin:$PATH
ENV GOPATH /go

WORKDIR ${workdir}

# hadolint ignore=DL3018
RUN apk add --no-cache \
    git \
    && git clone --depth 1 --branch ${opentf_branch} https://github.com/opentofu/opentofu.git ${workdir}

WORKDIR ${workdir}/cmd/tofu

RUN CGO_ENABLED=0 GOOS=${build_os} GOARCH=${build_arch} go build -a -ldflags "-w -s -extldflags '-static' -X 'main.experimentsAllowed=yes'" -o /bin/tofu

FROM ghcr.io/iodeslykos/alpine:latest@sha256:d4fbf66975246fe12dd71d344d344a1456190bbf6d480a96d269209c84ff9186 AS final

COPY --from=builder /bin/tofu /usr/local/bin/tofu

ENTRYPOINT [ "tofu" ]
CMD [ "--help" ]
