FROM golang:alpine@sha256:6c5c9590f169f77c8046e45c611d3b28fe477789acd8d3762d23d4744de69812 AS builder

LABEL org.opencontainers.image.title="opentofu"
LABEL org.opencontainers.image.authors="iodeslykos <42@iodeslykos.com>"
LABEL org.opencontainers.image.url="https://opentofu.org"
LABEL org.opencontainers.image.source="https://github.com/opentofu/opentofu/"

ARG build_arch=amd64
ARG build_os=linux
ARG workdir=/go/src/github.com/opentofu/opentofu
ARG opentf_branch=main

ENV PATH /go/bin:/usr/local/go/bin:$PATH
ENV GOPATH /go

WORKDIR ${workdir}

# hadolint ignore=DL3018
RUN apk add --no-cache \
    git \
    && git clone --depth 1 --branch ${opentf_branch} https://github.com/opentofu/opentofu.git ${workdir}

WORKDIR ${workdir}/cmd/tofu

RUN CGO_ENABLED=0 GOOS=${build_os} GOARCH=${build_arch} go build -a -ldflags "-w -s -extldflags '-static' -X 'main.experimentsAllowed=yes'" -o /bin/tofu

FROM ghcr.io/iodeslykos/alpine:latest@sha256:e90a63733596ef56a770831e620c7b805529ad52c1c5d636c5c3db549c6cafa6 AS final

COPY --from=builder /bin/tofu /usr/local/bin/tofu

ENTRYPOINT [ "tofu" ]
CMD [ "--help" ]
