apiVersion: v1
kind: Pod
metadata:
  name: kubectl
  namespace: kube-system
spec:
  containers:
  - name: kubectl
    image: ghcr.io/iodeslykos/kubectl:latest
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
