# hadolint global ignore=DL3007,SC2086
FROM ghcr.io/iodeslykos/debian:latest AS base

ENV USER=outis
ENV GROUP=outis
ENV UID=1000
ENV GID=1000
ENV BUILDAH_ISOLATION=chroot
ENV CONTAINERS_LOCAL_PATH=/home/${USER}/.local/share/containers
ENV CONTAINERS_CONFIG_PATH=/home/${USER}/.config/containers
ENV _CONTAINERS_USERNS_CONFIGURED=""

VOLUME "${CONTAINERS_LOCAL_PATH}" /var/lib/containers

# hadolint ignore=DL3008
RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y --no-install-recommends \
      buildah \
      bzip2 \
      containers-storage \
      crun \
      curl \
      fuse-overlayfs \
      jq \
      qemu-user-static \
      libcap2-bin \
      podman \
      skopeo \
    && setcap cap_setuid=ep /usr/bin/newuidmap \
    && setcap cap_setgid=ep /usr/bin/newgidmap \
    && apt-get autoremove --purge -y libcap2-bin \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN chmod 0777 /etc/subuid /etc/subgid && \
    # usermod --add-subuids 5000-165536 --add-subgids 5000-165536 ${USER}
    echo outis:5000:10000 > /etc/subuid && \
    echo outis:5000:10000 > /etc/subgid

RUN mkdir -p "${CONTAINERS_LOCAL_PATH}" /var/lib/containers/storage \
    && chown -R ${UID}:${GID} "${CONTAINERS_LOCAL_PATH}" /var/lib/containers/storage /home/${USER}

# storage.conf provided by containers-storage package for Debian 12 overlayfs support.
# COPY --chown=${UID}:${GID} storage.conf           /etc/containers/storage.conf
# COPY --chown=${UID}:${GID} containers.conf        /etc/containers/containers.conf
# COPY --chown=${UID}:${GID} registries.conf        /etc/containers/registries.conf
# COPY --chown=${UID}:${GID} podman-containers.conf /etc/containers/podman-containers.conf
# COPY --chown=${UID}:${GID} containers.conf        ${CONTAINERS_PATH}/containers.conf
# COPY --chown=${UID}:${GID} registries.conf        ${CONTAINERS_PATH}/registries.conf
# COPY --chown=${UID}:${GID} podman-containers.conf ${CONTAINERS_PATH}/podman-containers.conf
# COPY --chown=${UID}:${GID} entrypoint.sh          /entrypoint.sh

COPY --chmod=0644 containers.conf        /etc/containers/containers.conf
COPY --chmod=0644 registries.conf        /etc/containers/registries.conf
COPY --chmod=0644 podman-containers.conf /etc/containers/podman-containers.conf
COPY --chmod=0644 containers.conf        ${CONTAINERS_CONFIG_PATH}/containers.conf
COPY --chmod=0644 registries.conf        ${CONTAINERS_CONFIG_PATH}/registries.conf
COPY --chmod=0644 podman-containers.conf ${CONTAINERS_CONFIG_PATH}/podman-containers.conf
COPY --chmod=0755 entrypoint.sh          /home/${USER}/entrypoint.sh

RUN chmod +x /home/${USER}/entrypoint.sh && \
    chmod 0755 /usr/bin/fusermount3 && \
    mkdir -p /var/lib/shared/vfs-images \
             /var/lib/shared/vfs-layers \
             /var/lib/shared/overlay-images \
             /var/lib/shared/overlay-layers \
    && \
    touch /var/lib/shared/vfs-images/images.lock \
          /var/lib/shared/vfs-layers/layers.lock \
          /var/lib/shared/overlay-images/images.lock \
          /var/lib/shared/overlay-layers/layers.lock \
    && \
    buildah --version && \
    podman --version && \
    skopeo --version

USER ${USER}
WORKDIR /home/${USER}

ENTRYPOINT ["./entrypoint.sh"]
