FROM golang:alpine@sha256:2c49857f2295e89b23b28386e57e018a86620a8fede5003900f2d138ba9c4037 AS builder

LABEL org.opencontainers.image.title="opentofu"
LABEL org.opencontainers.image.authors="iodeslykos <42@iodeslykos.com>"
LABEL org.opencontainers.image.url="https://opentofu.org"
LABEL org.opencontainers.image.source="https://github.com/opentofu/opentofu/"

ARG build_arch=amd64
ARG build_os=linux
ARG workdir=/go/src/github.com/opentofu/opentofu
ARG opentf_branch=main

ENV PATH /go/bin:/usr/local/go/bin:$PATH
ENV GOPATH /go

WORKDIR ${workdir}

# hadolint ignore=DL3018
RUN apk add --no-cache \
    git \
    && git clone --depth 1 --branch ${opentf_branch} https://github.com/opentofu/opentofu.git ${workdir}

WORKDIR ${workdir}/cmd/tofu

RUN CGO_ENABLED=0 GOOS=${build_os} GOARCH=${build_arch} go build -a -ldflags "-w -s -extldflags '-static' -X 'main.experimentsAllowed=yes'" -o /bin/tofu

FROM ghcr.io/iodeslykos/alpine:latest@sha256:1abaf4bb842a012a2225d782a6692daf1678edf6fea9b3557c6d3d8974232592 AS final

COPY --from=builder /bin/tofu /usr/local/bin/tofu

ENTRYPOINT [ "tofu" ]
CMD [ "--help" ]
