name: "Build base images."

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: [push, pull_request]

jobs:
  build-base-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        platforms:
          - linux/amd64
          - linux/arm64
        images:
          - dockerfile: base/al2023/Dockerfile
            directory: base/al2023
            image: ghcr.io/${{ github.repository }}/al2023:latest
          - dockerfile: base/alpine/Dockerfile
            directory: base/alpine
            image: ghcr.io/${{ github.repository }}/alpine:latest
          - dockerfile: base/debian/Dockerfile
            directory: base/debian
            image: ghcr.io/${{ github.repository }}/debian:latest
    outputs:
      digests: ${{ steps.push-image.outputs.digest }}
    steps:
      - name: "Checkout repository."
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Set up QEMU."
        uses: docker/setup-qemu-action@v2
      - name: "Set up Docker Buildx."
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ matrix.platforms }}
      - name: "Login: ghcr.io"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Push image."
        id: push-image
        uses: docker/build-push-action@v5
        with:
          context:
          file: ${{ matrix.images.dockerfile }}
          push: true
          tags: ${{ matrix.images.image }}
          platforms: ${{ matrix.platforms }}
          labels: |-
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.source=https://github.com/${{ github.repository}}
